---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: konnectivity-agent
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
