name: Release Charts

on:
  workflow_dispatch: {}
  release: {}

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Set Version
        run: |
          TAG=$(git describe --tags --abbrev=0)
          sed -ie "s/appVersion: \"latest\"/appVersion: ${TAG#helm-}/g" chart/Chart.yaml
          sed -ie "s/version: 0.0.0/version: ${TAG#helm-}/g" chart/Chart.yaml

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-{{ .Version }}"
        with:
          charts_dir: .
          skip_existing: true
